// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

type Attribute struct {
	AttributeID     int64
	EntityID        int64
	AttributeTypeID int64
	AttributeValue  string
}

type AttributeType struct {
	AttributeTypeID   int64
	AttributeTypeName string
}

type Communication struct {
	CommunicationID          int64
	EntityID                 int64
	CommunicationName        string
	CommunicationDestination string
	CommunicationTypeID      int64
}

type CommunicationType struct {
	CommunicationTypeID   int64
	CommunicationTypeName string
}

type Entity struct {
	EntityID     int64
	EntityName   string
	EntityTypeID int64
}

type EntityType struct {
	EntityTypeID   int64
	EntityTypeName string
}

type Relationship struct {
	RelationshipID     int64
	SourceEntityID     int64
	TargetEntityID     int64
	RelationshipTypeID int64
}

type RelationshipType struct {
	RelationshipTypeID   int64
	RelationshipTypeName string
}

type SourceEntity struct {
	EntityID     int64
	EntityName   string
	EntityTypeID int64
}

type SourceEntityType struct {
	EntityTypeID   int64
	EntityTypeName string
}

type TargetEntity struct {
	EntityID     int64
	EntityName   string
	EntityTypeID int64
}

type TargetEntityType struct {
	EntityTypeID   int64
	EntityTypeName string
}
